/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://la33nbdvozgtvkyb4tb7kecztu.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ixq3ehshdzeitbvql5tutu64jy",
    "aws_cognito_identity_pool_id": "us-west-2:f53e8cfc-ec9a-4473-9154-386076790a97",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_exchTZcrW",
    "aws_user_pools_web_client_id": "4jhu5aj4r2lqa1puuvrr04ff9k",
    "oauth": {}
};


export default awsmobile;
